Allow to build native on arm platform

diff --git a/rootstock-touch b/rootstock-touch
--- a/rootstock-touch
+++ b/rootstock-touch
@@ -41,6 +41,7 @@ DO_PPA=
 PREINSTALLED="true"
 IMAGEFORMAT="plain"
 PROJECT_="ubports-touch"
+HOSTARCH=$(dpkg-architecture -qDEB_HOST_ARCH)
 CHROOT=$(mktemp -d /tmp/rootstock.XXXXX)
 
 [ ! $(which qemu-debootstrap) ] && echo "please install the qemu-user-static package" && exit 1
@@ -123,16 +124,34 @@ done
 
 case $ARCH in
 	i386|amd64)
-		MIRROR="${MIRROR:-http://archive.ubuntu.com/ubuntu}"
-		BOOTSTRAP_BIN="debootstrap --arch $ARCH"
-		LB_BOOTSTRAP_QEMU_ARCHITECTURES=""
-		LB_BOOTSTRAP_QEMU_STATIC=""
+		case $HOSTARCH in
+			armhf|arm64)
+				echo "arm machine cannot build i386 or amd64"
+				exit 1
+				;;
+			*)
+				MIRROR="${MIRROR:-http://archive.ubuntu.com/ubuntu}"
+				BOOTSTRAP_BIN="debootstrap --arch $ARCH"
+				LB_BOOTSTRAP_QEMU_ARCHITECTURES=""
+				LB_BOOTSTRAP_QEMU_STATIC=""
+				;;
+		esac
 		;;
 	armhf)
-		MIRROR="${MIRROR:-http://ports.ubuntu.com/ubuntu-ports}"
-		BOOTSTRAP_BIN="qemu-debootstrap --arch armhf --variant=minbase"
-		LB_BOOTSTRAP_QEMU_ARCHITECTURES="armhf"
-		LB_BOOTSTRAP_QEMU_STATIC="/usr/bin/qemu-arm-static"
+		case $HOSTARCH in
+			armhf|arm64)
+				MIRROR="${MIRROR:-http://ports.ubuntu.com/ubuntu-ports}"
+				BOOTSTRAP_BIN="debootstrap --arch $ARCH --variant=minbase"
+				LB_BOOTSTRAP_QEMU_ARCHITECTURES=""
+				LB_BOOTSTRAP_QEMU_STATIC=""
+				;;
+			*)
+				MIRROR="${MIRROR:-http://ports.ubuntu.com/ubuntu-ports}"
+				BOOTSTRAP_BIN="qemu-debootstrap --arch armhf --variant=minbase"
+				LB_BOOTSTRAP_QEMU_ARCHITECTURES="armhf"
+				LB_BOOTSTRAP_QEMU_STATIC="/usr/bin/qemu-arm-static"
+				;;
+		esac
 		;;
 	*)
 		usage
